# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 698557380bbdb6915de5c12f13283eb89e543fe2538ded908b100d38ee32eafd51fc90edf7e28bc1727aa6f4218573545563b71668ad5c95ea17e67773dfea75

test:
  secret_key_base: 0cf008efd08eb5b0fd27a20876db446a86c656eb1167f9f248a1ab822f9ff366c54be009613baca6f5dd17b05ec305c6860e9398d8696e7abcd80cc993d77522

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
